package com.example.dllo.vmovie.dbtool;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "SUB_SCRIBE_BEAN".
 */
@Entity
public class SubScribeBean {

    @Id(autoincrement = true)
    private Long id;
    private String seriesId;

    @Generated
    public SubScribeBean() {
    }

    public SubScribeBean(Long id) {
        this.id = id;
    }

    @Generated
    public SubScribeBean(Long id, String seriesId) {
        this.id = id;
        this.seriesId = seriesId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSeriesId() {
        return seriesId;
    }

    public void setSeriesId(String seriesId) {
        this.seriesId = seriesId;
    }

}
