package com.example.dllo.vmovie.dbtool;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.example.dllo.vmovie.dbtool.DaoSession;
import com.example.dllo.vmovie.dbtool.SubScribeBean;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SUB_SCRIBE_BEAN".
*/
public class SubScribeBeanDao extends AbstractDao<SubScribeBean, Long> {

    public static final String TABLENAME = "SUB_SCRIBE_BEAN";

    /**
     * Properties of entity SubScribeBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SeriesId = new Property(1, String.class, "seriesId", false, "SERIES_ID");
    }


    public SubScribeBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SubScribeBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SUB_SCRIBE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SERIES_ID\" TEXT);"); // 1: seriesId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SUB_SCRIBE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SubScribeBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String seriesId = entity.getSeriesId();
        if (seriesId != null) {
            stmt.bindString(2, seriesId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SubScribeBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String seriesId = entity.getSeriesId();
        if (seriesId != null) {
            stmt.bindString(2, seriesId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SubScribeBean readEntity(Cursor cursor, int offset) {
        SubScribeBean entity = new SubScribeBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // seriesId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SubScribeBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSeriesId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SubScribeBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SubScribeBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SubScribeBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
